### ISSUE TITLE
Problem in menu slot

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Cashier#13]
The slot on line https://github.com/StarcounterApps/Cashier/blob/586a3bd60764b828dcab1ad3ff75bfc7d85b0326/src/Cashier/wwwroot/Cashier/viewmodels/MenuPage.html will not work, because it is not on the view root element.

The slot attribute should be set on `<li>`.

**Comment by PatrykSzwer** [comment]
Fixed in #14. Closing.
