### ISSUE TITLE
Change fields to properties in all database classes

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Cashier#18]
As requested in https://github.com/Starcounter/TechComm/issues/340, change fields to properties in all `[Database]` classes in this repo.

Scheduled after https://github.com/StarcounterApps/Simplified/issues/53

**Comment by Mihaiii** [comment]
Table `Cashier.Settings` doesn't exists ([line](https://github.com/StarcounterApps/Cashier/blob/master/src/Cashier/Api/MainHandlers.cs#L97)).

**Comment by warpech** [comment]
I can see it is defined here: https://github.com/StarcounterApps/Cashier/blob/be341b6f5fdcbbd1f3889d91a70f92fc8333dae6/src/Cashier/Database/Settings.cs

**Comment by Mihaiii** [comment]
Close as done.
