### ISSUE TITLE
A slot attribute is at a wrong level

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Cashier#23]
The slot name on the element `starcounter-include` will not work, because that element is not on the template root:

https://github.com/StarcounterApps/Cashier/blob/c7885f029b02d4349e006c1d99a2ac3227988e31/src/Cashier/wwwroot/Cashier/viewmodels/MasterPage.html#L19

The `div` should be moved to Shadow DOM.

I know it was like that even before https://github.com/StarcounterApps/Cashier/pull/21, but that was wrong.

cc @Mackiovello, @PatrykSzwer, @bouguila

**Comment by Mihaiii** [comment]
Closing as done.
